import { DataGrid } from '@mui/x-data-grid';
import React, { useEffect, useState } from 'react';
import CustomToolbar from '../shared/CustomToolbar';

const columns = [
  { field: 'name', headerName: 'Project Name', width: 150 },
  { field: 'createdBy', headerName: 'Created By', width: 150 },
  { field: 'equipments', headerName: 'Equipments', width: 150 },
  { field: 'startDate', headerName: 'Start Date', width: 150 },
  { field: 'deadline', headerName: 'Deadline', width: 150 },
  { field: 'contributor', headerName: 'Contributor', width: 150 },
  { field: 'status', headerName: 'Status', width: 150 },
  { field: 'tags', headerName: 'Tags', width: 150 },
  { field: 'requirements', headerName: 'Requirements', width: 150 },
  { field: 'addRequirements', headerName: 'Add Requirements', width: 150 },
  {
    headerName: 'Actions',
    width: 200,
    renderCell: () => {
      return (
        <div className='flex gap-x-1'>
          <button className='bg-purple-500 text-white px-2 py-1 rounded'>
            Edit
          </button>
          <button className='bg-green-500 text-white px-2 py-1 rounded'>
            Active
          </button>
          <button className='bg-red-500 text-white px-2 py-1 rounded'>
            Delete
          </button>
        </div>
      );
    },
  },
];
const Table = () => {
  const [pageSize, setPageSize] = React.useState(5);
  const [data, setData] = useState([]);
  const [filterData, setFilterData] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  useEffect(() => {
    setData(allData);
    setFilterData(allData);
  }, []);

  useEffect(() => {
    const columnsProps = [
      'name',
      'createdBy',
      'equipments',
      'contributor',
      'tags',
      'requirements',
      'addRequirements',
      'startDate',
    ];
    const filterData = () => {
      const filterIds = columnsProps
        .map((col) => {
          const colWiseData = data.map((item) => {
            return { id: item.id, data: item[col], col };
          });
          const searchItem = colWiseData
            .filter((item) => {
              if (
                item.data
                  .toLowerCase()
                  .includes(searchTerm.trim().toLowerCase())
              ) {
                return true;
              }
              return false;
            })
            .map((item) => item.id);
          return searchItem;
        })
        .flat(Infinity);
      const uniqueFilterIdes = Array.from(new Set([...filterIds]));
      const filterItems = data.filter((item) =>
        uniqueFilterIdes.includes(item.id)
      );

      return filterItems;
    };

    setFilterData(filterData());
    return () => filterData();
  }, [searchTerm, data]);
  const searchTermOnChange = (event) => {
    if (event.target.value !== searchTerm) {
      setSearchTerm(event.target.value);
    }
  };

  return (
    <div
      style={{ height: pageSize > 15 ? 700 : 500, width: '100%' }}
      className='mt-5'
    >
      <DataGrid
        rows={filterData}
        columns={columns}
        disableSelectionOnClick
        checkboxSelection
        disableColumnMenu
        pageSize={pageSize}
        onPageSizeChange={(newPageSize) => setPageSize(newPageSize)}
        rowsPerPageOptions={[5, 10, 20, 30, 50]}
        pagination
        components={{ Toolbar: CustomToolbar }}
        componentsProps={{
          toolbar: {
            data,
            columns,
            searchTerm,
            onChange: searchTermOnChange,
          },
        }}
        style={{ border: 'none' }}
      />
    </div>
  );
};

export default Table;

const allData = [
  {
    id: 1,
    name: 'Buzzbean',
    equipments: 'Osinski and Sons',
    startDate: '8/6/2020',
    deadline: '1/24/2022',
    contributor:
      'Solidago uliginosa Nutt. var. terrae-novae (Torr. & A. Gray) Fernald',
    status: false,
    tags: 'Eagle',
    requirements: '5.3',
    addRequirements: 'com.constantcontact.Transcof',
    createdBy: 'Bert Bossons',
  },
  {
    id: 2,
    name: 'Jayo',
    equipments: 'Prohaska Inc',
    startDate: '5/14/2020',
    deadline: '7/3/2021',
    contributor: 'Acroceras macrum Stapf',
    status: false,
    tags: 'BMW',
    requirements: '1.61',
    addRequirements: 'com.skype.Redhold',
    createdBy: 'Johan Luetkemeyers',
  },
  {
    id: 3,
    name: 'Devpoint',
    equipments: 'Bins Group',
    startDate: '4/25/2020',
    deadline: '5/24/2020',
    contributor: 'Cyanea pilosa A. Gray ssp. longipedunculata (Rock) Lammers',
    status: true,
    tags: 'Mitsubishi',
    requirements: '0.94',
    addRequirements: 'com.trellian.Subin',
    createdBy: 'Tobe Pauluzzi',
  },
  {
    id: 4,
    name: 'Oyoba',
    equipments: 'Bradtke, Balistreri and Morar',
    startDate: '12/11/2020',
    deadline: '8/23/2021',
    contributor: 'Vesicularia (Müll. Hal.) Müll. Hal.',
    status: true,
    tags: 'Dodge',
    requirements: '0.8.6',
    addRequirements: 'com.mozilla.Alpha',
    createdBy: 'Kelsi Cahill',
  },
  {
    id: 5,
    name: 'Edgewire',
    equipments: 'Padberg and Sons',
    startDate: '4/22/2021',
    deadline: '9/19/2020',
    contributor:
      'Machaeranthera grindelioides (Nutt.) Shinners var. depressa (Maguire) Cronquist & D.D. Keck',
    status: false,
    tags: 'Ford',
    requirements: '7.7',
    addRequirements: 'com.ft.Latlux',
    createdBy: 'Dorothy Brevitt',
  },
  {
    id: 6,
    name: 'Jayo',
    equipments: 'Jakubowski and Sons',
    startDate: '2/17/2022',
    deadline: '5/5/2021',
    contributor: 'Cylindropuntia spinosior (Engelm.) F.M. Knuth',
    status: false,
    tags: 'Chevrolet',
    requirements: '0.80',
    addRequirements: 'gl.goo.Bitwolf',
    createdBy: 'Barri Weare',
  },
  {
    id: 7,
    name: 'Voomm',
    equipments: 'Simonis, Kuvalis and Ledner',
    startDate: '12/9/2021',
    deadline: '1/27/2021',
    contributor: 'Bidens leptocephala Sherff',
    status: false,
    tags: 'Land Rover',
    requirements: '2.28',
    addRequirements: 'com.canalblog.Ronstring',
    createdBy: 'Adriana Lucio',
  },
  {
    id: 8,
    name: 'Divape',
    equipments: 'Nader, Bruen and Ledner',
    startDate: '4/12/2021',
    deadline: '10/9/2020',
    contributor: 'Penstemon putus A. Nelson',
    status: true,
    tags: 'Chrysler',
    requirements: '0.75',
    addRequirements: 'jp.ne.so-net.Y-Solowarm',
    createdBy: 'Abbey Weddell',
  },
  {
    id: 9,
    name: 'Livetube',
    equipments: 'Funk, Davis and Kassulke',
    startDate: '5/28/2021',
    deadline: '5/2/2020',
    contributor: 'Anthemis austriaca Jacq.',
    status: true,
    tags: 'Volkswagen',
    requirements: '0.1.2',
    addRequirements: 'de.t-online.Prodder',
    createdBy: 'Cassi Garry',
  },
  {
    id: 10,
    name: 'InnoZ',
    equipments: 'Halvorson Group',
    startDate: '1/9/2022',
    deadline: '8/21/2020',
    contributor: 'Phlox speciosa Pursh ssp. nitida (Suksd.) Wherry',
    status: false,
    tags: 'Dodge',
    requirements: '4.1',
    addRequirements: 'com.bizjournals.Rank',
    createdBy: 'Rickie Tyas',
  },
  {
    id: 11,
    name: 'Riffpath',
    equipments: 'Stroman and Sons',
    startDate: '9/23/2020',
    deadline: '4/7/2021',
    contributor: 'Parmotrema chinense (Osbeck) Hale & Ahti',
    status: false,
    tags: 'Lincoln',
    requirements: '2.1.4',
    addRequirements: 'com.blogspot.Fix San',
    createdBy: 'Gayla Dugget',
  },
  {
    id: 12,
    name: 'Zoombox',
    equipments: 'Anderson-Windler',
    startDate: '1/21/2021',
    deadline: '9/13/2020',
    contributor: 'Tephrosia mohrii (Rydb.) Godfrey',
    status: true,
    tags: 'Volkswagen',
    requirements: '0.76',
    addRequirements: 'pl.google.Temp',
    createdBy: 'Darelle Yeld',
  },
  {
    id: 13,
    name: 'Devpulse',
    equipments: 'McKenzie, Wolf and Collier',
    startDate: '6/29/2021',
    deadline: '11/22/2021',
    contributor: 'Stellaria prostrata Baldw.',
    status: true,
    tags: 'Aston Martin',
    requirements: '0.23',
    addRequirements: 'com.mlb.Asoka',
    createdBy: 'Obidiah Grishakin',
  },
  {
    id: 14,
    name: 'Skyndu',
    equipments: 'Cartwright-Herzog',
    startDate: '12/2/2020',
    deadline: '12/5/2020',
    contributor: 'Hypnum Hedw.',
    status: true,
    tags: 'Audi',
    requirements: '2.16',
    addRequirements: 'org.wordpress.Tres-Zap',
    createdBy: 'Sena Stripling',
  },
  {
    id: 15,
    name: 'Browsezoom',
    equipments: 'Huels, Russel and Breitenberg',
    startDate: '3/11/2021',
    deadline: '11/20/2020',
    contributor: 'Plantago L.',
    status: false,
    tags: 'Pontiac',
    requirements: '0.40',
    addRequirements: 'com.lycos.Stronghold',
    createdBy: 'Ollie Dabs',
  },
  {
    id: 16,
    name: 'Realmix',
    equipments: 'Dietrich-Mante',
    startDate: '9/10/2020',
    deadline: '1/19/2021',
    contributor: 'Phalaris brachystachys Link',
    status: true,
    tags: 'Mitsubishi',
    requirements: '0.54',
    addRequirements: 'uk.co.thetimes.Regrant',
    createdBy: 'Alisun Askew',
  },
  {
    id: 17,
    name: 'Dabjam',
    equipments: 'Nienow, Morissette and Windler',
    startDate: '6/12/2021',
    deadline: '1/27/2021',
    contributor: 'Xanthoparmelia neotaractica Hale',
    status: false,
    tags: 'Nissan',
    requirements: '2.15',
    addRequirements: 'com.statcounter.Pannier',
    createdBy: 'Petronia Warton',
  },
  {
    id: 18,
    name: 'Shufflebeat',
    equipments: 'Reynolds, Carter and Dietrich',
    startDate: '2/20/2021',
    deadline: '12/31/2021',
    contributor:
      'Tetraneuris scaposa (DC.) Greene var. villosa (Shinners) Shinners',
    status: true,
    tags: 'Toyota',
    requirements: '3.6.5',
    addRequirements: 'org.altervista.Tresom',
    createdBy: 'Abigail Tebbit',
  },
  {
    id: 19,
    name: 'Edgewire',
    equipments: 'Beier-Schroeder',
    startDate: '11/3/2021',
    deadline: '12/10/2020',
    contributor:
      'Oreostemma alpigenum (Torr. & A. Gray) Greene var. andersonii (A. Gray) G.L. Nesom',
    status: true,
    tags: 'GMC',
    requirements: '0.49',
    addRequirements: 'com.macromedia.Gembucket',
    createdBy: 'Ayn Kernocke',
  },
  {
    id: 20,
    name: 'InnoZ',
    equipments: 'Gleichner, Gutmann and Carter',
    startDate: '8/19/2020',
    deadline: '1/28/2021',
    contributor: 'Pouteria sandwicensis (A. Gray) Baehni & O. Deg.',
    status: true,
    tags: 'Chevrolet',
    requirements: '2.1.9',
    addRequirements: 'com.hp.Zathin',
    createdBy: 'Aylmer MacTrustey',
  },
  {
    id: 21,
    name: 'Vinte',
    equipments: 'Hyatt LLC',
    startDate: '10/27/2020',
    deadline: '9/3/2021',
    contributor: 'Kallstroemia parviflora J.B.S. Norton',
    status: false,
    tags: 'Toyota',
    requirements: '0.5.8',
    addRequirements: 'com.dedecms.Fix San',
    createdBy: 'Fan Colecrough',
  },
  {
    id: 22,
    name: 'Blogpad',
    equipments: 'Lynch-Fadel',
    startDate: '2/25/2022',
    deadline: '9/12/2020',
    contributor: 'Acourtia microcephala DC.',
    status: false,
    tags: 'Mitsubishi',
    requirements: '8.14',
    addRequirements: 'com.bloglines.Namfix',
    createdBy: 'Galina Brunon',
  },
  {
    id: 23,
    name: 'Livefish',
    equipments: 'Haag-Ebert',
    startDate: '11/2/2021',
    deadline: '3/21/2021',
    contributor: 'Arabis breweri S. Watson var. breweri',
    status: false,
    tags: 'Aston Martin',
    requirements: '8.8.4',
    addRequirements: 'jp.co.rakuten.It',
    createdBy: 'Karrah Duncan',
  },
  {
    id: 24,
    name: 'Skipstorm',
    equipments: 'VonRueden Group',
    startDate: '10/30/2021',
    deadline: '11/28/2020',
    contributor: 'Plagiobothrys parishii I.M. Johnst.',
    status: true,
    tags: 'Lotus',
    requirements: '5.5.7',
    addRequirements: 'net.clickbank.Bitwolf',
    createdBy: 'Gretel Heinert',
  },
  {
    id: 25,
    name: 'Skipfire',
    equipments: 'Nikolaus Inc',
    startDate: '12/2/2020',
    deadline: '4/24/2021',
    contributor: 'Calochortus weedii Alph. Wood var. intermedius Ownbey',
    status: false,
    tags: 'GMC',
    requirements: '3.74',
    addRequirements: 'cz.mapy.Alpha',
    createdBy: 'Crissy Amsden',
  },
  {
    id: 26,
    name: 'Pixope',
    equipments: 'Skiles, McKenzie and Wiza',
    startDate: '9/22/2020',
    deadline: '2/16/2021',
    contributor: 'Opuntia rufida Engelm.',
    status: true,
    tags: 'GMC',
    requirements: '9.6',
    addRequirements: 'au.net.abc.Cardguard',
    createdBy: 'Eugenio Kell',
  },
  {
    id: 27,
    name: 'Buzzshare',
    equipments: "D'Amore Inc",
    startDate: '2/16/2022',
    deadline: '8/14/2021',
    contributor: 'Carex ×quebecensis Lepage',
    status: false,
    tags: 'Chevrolet',
    requirements: '4.75',
    addRequirements: 'com.foxnews.Ronstring',
    createdBy: 'Daffi Vedekhov',
  },
  {
    id: 28,
    name: 'Rhybox',
    equipments: 'Zemlak Inc',
    startDate: '9/2/2021',
    deadline: '7/5/2021',
    contributor: 'Kennedia prostrata R. Br.',
    status: false,
    tags: 'Audi',
    requirements: '0.6.2',
    addRequirements: 'com.wp.Stim',
    createdBy: 'Isa Bartel',
  },
  {
    id: 29,
    name: 'Buzzdog',
    equipments: 'Rolfson and Sons',
    startDate: '4/25/2020',
    deadline: '11/20/2021',
    contributor: 'Physaria integrifolia (Rollins) Lichvar var. integrifolia',
    status: false,
    tags: 'MINI',
    requirements: '0.90',
    addRequirements: 'com.angelfire.Vagram',
    createdBy: 'Taylor Castledine',
  },
  {
    id: 30,
    name: 'Skipfire',
    equipments: 'Hessel-Herzog',
    startDate: '6/23/2020',
    deadline: '5/14/2020',
    contributor: 'Lecidea tenuissima Lynge',
    status: false,
    tags: 'Oldsmobile',
    requirements: '0.16',
    addRequirements: 'org.drupal.Flowdesk',
    createdBy: 'Ilene Dummigan',
  },
  {
    id: 31,
    name: 'Demimbu',
    equipments: 'Osinski-Harber',
    startDate: '5/4/2020',
    deadline: '1/19/2021',
    contributor: 'Galeopsis speciosa Mill.',
    status: true,
    tags: 'GMC',
    requirements: '5.3.2',
    addRequirements: 'com.seattletimes.Trippledex',
    createdBy: 'Maxy MacAscaidh',
  },
  {
    id: 32,
    name: 'Oyoloo',
    equipments: 'Kiehn, Torp and Cartwright',
    startDate: '2/2/2022',
    deadline: '8/7/2021',
    contributor: 'Cordia dichotoma G. Forst.',
    status: true,
    tags: 'Mercedes-Benz',
    requirements: '0.48',
    addRequirements: 'com.indiatimes.Andalax',
    createdBy: 'Ellwood Bernardelli',
  },
  {
    id: 33,
    name: 'Jabberstorm',
    equipments: 'Bradtke-Mraz',
    startDate: '5/7/2021',
    deadline: '8/30/2021',
    contributor: 'Calochortus bruneaunis A. Nelson & J.F. Macbr.',
    status: false,
    tags: 'Chevrolet',
    requirements: '7.3',
    addRequirements: 'com.digg.Stringtough',
    createdBy: 'Linda Locock',
  },
  {
    id: 34,
    name: 'Oyonder',
    equipments: 'Schultz LLC',
    startDate: '3/3/2021',
    deadline: '8/21/2020',
    contributor: 'Bulbostylis Kunth',
    status: true,
    tags: 'Oldsmobile',
    requirements: '2.53',
    addRequirements: 'edu.tamu.Temp',
    createdBy: "Jemimah D'Andrea",
  },
  {
    id: 35,
    name: 'Jaloo',
    equipments: 'Rice-Russel',
    startDate: '6/4/2020',
    deadline: '10/9/2021',
    contributor:
      'Melanthera aspera (Jacq.) Steud. ex Small var. glabriuscula (Kuntze) J.C. Parks',
    status: false,
    tags: 'Oldsmobile',
    requirements: '0.5.1',
    addRequirements: 'org.bbb.Zamit',
    createdBy: 'Pearla Reims',
  },
  {
    id: 36,
    name: 'Devpoint',
    equipments: 'Conroy, Rippin and Harvey',
    startDate: '10/26/2020',
    deadline: '8/3/2021',
    contributor:
      'Hackelia deflexa (Wahlenb.) Opiz var. americana (A. Gray) Fernald & I.M. Johnst.',
    status: false,
    tags: 'Buick',
    requirements: '0.9.4',
    addRequirements: 'org.networkadvertising.Latlux',
    createdBy: 'Cherey Patrick',
  },
  {
    id: 37,
    name: 'Livepath',
    equipments: 'Powlowski, Smith and Fay',
    startDate: '2/23/2021',
    deadline: '12/10/2021',
    contributor:
      'Miscanthus ×giganteus J.M. Greef & Deuter ex Hodkinson & Renvoize',
    status: true,
    tags: 'BMW',
    requirements: '0.11',
    addRequirements: 'de.1und1.Cardguard',
    createdBy: 'Emmott Lyptrade',
  },
  {
    id: 38,
    name: 'Ainyx',
    equipments: 'Jaskolski Inc',
    startDate: '12/13/2021',
    deadline: '2/8/2022',
    contributor: 'Salix melanopsis Nutt.',
    status: false,
    tags: 'Volkswagen',
    requirements: '0.34',
    addRequirements: 'com.adobe.Ventosanzap',
    createdBy: 'Cleve Kanter',
  },
  {
    id: 39,
    name: 'Realpoint',
    equipments: 'Christiansen-Jerde',
    startDate: '1/29/2022',
    deadline: '11/28/2021',
    contributor:
      'Dyschoriste linearis (Torr. & A. Gray) Kuntze var. sanpatriciensis Henrickson',
    status: true,
    tags: 'Audi',
    requirements: '0.4.1',
    addRequirements: 'de.t-online.Y-find',
    createdBy: 'Atlante Redsell',
  },
  {
    id: 40,
    name: 'Rhybox',
    equipments: 'Carroll LLC',
    startDate: '7/26/2021',
    deadline: '7/17/2020',
    contributor: 'Dicranum muehlenbeckii Bruch & Schimp.',
    status: true,
    tags: 'Mercury',
    requirements: '5.46',
    addRequirements: 'com.barnesandnoble.Tres-Zap',
    createdBy: 'Krystal Schroder',
  },
  {
    id: 41,
    name: 'Quamba',
    equipments: 'Steuber and Sons',
    startDate: '7/11/2020',
    deadline: '9/2/2020',
    contributor:
      'Townsendia condensata Parry ex A. Gray var. anomala (Heiser) Dorn',
    status: false,
    tags: 'Volkswagen',
    requirements: '7.7',
    addRequirements: 'com.newsvine.Zaam-Dox',
    createdBy: 'Tandy McLugaish',
  },
  {
    id: 42,
    name: 'Zoombeat',
    equipments: 'Pagac, Torp and Olson',
    startDate: '1/16/2022',
    deadline: '11/14/2021',
    contributor: 'Ptelea trifoliata L. ssp. trifoliata',
    status: true,
    tags: 'Aston Martin',
    requirements: '0.19',
    addRequirements: 'com.tumblr.Zontrax',
    createdBy: 'Rodi Haquard',
  },
  {
    id: 43,
    name: 'Browseblab',
    equipments: 'Hettinger-Leffler',
    startDate: '9/3/2020',
    deadline: '12/9/2021',
    contributor: 'Pentaclethra macrophylla Benth.',
    status: true,
    tags: 'Mercedes-Benz',
    requirements: '7.6',
    addRequirements: 'com.blinklist.Quo Lux',
    createdBy: 'Myer Eade',
  },
  {
    id: 44,
    name: 'Voonte',
    equipments: 'McGlynn Group',
    startDate: '5/26/2020',
    deadline: '5/16/2020',
    contributor: 'Saxifraga caespitosa L. ssp. caespitosa',
    status: false,
    tags: 'GMC',
    requirements: '6.4.2',
    addRequirements: 'it.google.Opela',
    createdBy: 'Wolfy Feechan',
  },
  {
    id: 45,
    name: 'Tagchat',
    equipments: 'Botsford, Herman and Ferry',
    startDate: '5/30/2021',
    deadline: '2/18/2022',
    contributor: 'Alliaria Heist. ex Fabr.',
    status: true,
    tags: 'Subaru',
    requirements: '2.0.5',
    addRequirements: 'jp.ne.hatena.Zathin',
    createdBy: 'Rudyard Arthars',
  },
  {
    id: 46,
    name: 'Eamia',
    equipments: 'Funk-Bins',
    startDate: '4/12/2020',
    deadline: '7/15/2021',
    contributor: 'Ticanto Adans.',
    status: true,
    tags: 'Land Rover',
    requirements: '4.4',
    addRequirements: 'com.mozilla.Ventosanzap',
    createdBy: 'Cassi Godleman',
  },
  {
    id: 47,
    name: 'Lajo',
    equipments: 'Harris Inc',
    startDate: '10/23/2021',
    deadline: '2/24/2022',
    contributor: 'Quercus laceyi Small',
    status: true,
    tags: 'Subaru',
    requirements: '2.9',
    addRequirements: 'org.unesco.Stronghold',
    createdBy: 'Nilson Gateley',
  },
  {
    id: 48,
    name: 'Flipopia',
    equipments: 'Wiegand LLC',
    startDate: '2/23/2022',
    deadline: '9/23/2020',
    contributor: 'Polygonum L.',
    status: true,
    tags: 'Chevrolet',
    requirements: '9.9',
    addRequirements: 'com.adobe.Stim',
    createdBy: 'Ardis Mathieson',
  },
  {
    id: 49,
    name: 'Flashdog',
    equipments: 'Considine, Wunsch and Collins',
    startDate: '8/15/2021',
    deadline: '1/8/2022',
    contributor:
      'Lomatium salmoniflorum (J.M. Coult. & Rose) Mathias & Constance',
    status: false,
    tags: 'Cadillac',
    requirements: '5.9',
    addRequirements: 'gov.loc.Fintone',
    createdBy: 'Hansiain Gull',
  },
  {
    id: 50,
    name: 'Vitz',
    equipments: 'Gaylord Inc',
    startDate: '9/30/2021',
    deadline: '10/8/2021',
    contributor: 'Aronia ×prunifolia (Marshall) Rehder, (pro sp.)',
    status: true,
    tags: 'Porsche',
    requirements: '1.52',
    addRequirements: 'us.imageshack.Daltfresh',
    createdBy: 'Lissie Davy',
  },
  {
    id: 51,
    name: 'Shuffletag',
    equipments: 'Halvorson LLC',
    startDate: '1/30/2021',
    deadline: '1/13/2021',
    contributor: 'Jateorhiza palmata (Lam.) Miers',
    status: false,
    tags: 'Audi',
    requirements: '3.5',
    addRequirements: 'com.bing.Ronstring',
    createdBy: 'Daryl Jankowski',
  },
  {
    id: 52,
    name: 'Kimia',
    equipments: 'Wiza, Schuster and Wehner',
    startDate: '1/24/2022',
    deadline: '4/18/2021',
    contributor: 'Quercus ×wagneri Gaynor',
    status: true,
    tags: 'Pontiac',
    requirements: '0.3.2',
    addRequirements: 'edu.umn.Cookley',
    createdBy: 'Zane De Gogay',
  },
  {
    id: 53,
    name: 'Tagtune',
    equipments: 'Haley LLC',
    startDate: '11/22/2020',
    deadline: '2/22/2022',
    contributor:
      'Eubrachion ambiguum (Hook. & Arn.) Engl. var. jamaicense Krug & Urb.',
    status: true,
    tags: 'Chevrolet',
    requirements: '7.1',
    addRequirements: 'com.twitter.Namfix',
    createdBy: 'Sarge Hryskiewicz',
  },
  {
    id: 54,
    name: 'Skyba',
    equipments: 'Quigley and Sons',
    startDate: '4/11/2020',
    deadline: '1/24/2021',
    contributor: 'Pectis longipes A. Gray',
    status: true,
    tags: 'Toyota',
    requirements: '0.86',
    addRequirements: 'uk.co.amazon.Bitwolf',
    createdBy: 'Annalee Fawlo',
  },
  {
    id: 55,
    name: 'Twitternation',
    equipments: 'Ebert-Upton',
    startDate: '8/10/2020',
    deadline: '12/22/2021',
    contributor: 'Erigeron speciosus (Lindl.) DC. var. speciosus',
    status: false,
    tags: 'Mitsubishi',
    requirements: '0.83',
    addRequirements: 'gov.ed.Latlux',
    createdBy: 'Alfi Weldon',
  },
  {
    id: 56,
    name: 'Topicblab',
    equipments: 'Dach Inc',
    startDate: '1/25/2021',
    deadline: '1/30/2022',
    contributor:
      'Epilobium ciliatum Raf. ssp. glandulosum (Lehm.) Hoch & P.H. Raven',
    status: false,
    tags: 'Ford',
    requirements: '5.59',
    addRequirements: 'com.tripadvisor.Veribet',
    createdBy: 'Kenny Pryn',
  },
  {
    id: 57,
    name: 'Brainbox',
    equipments: 'Brakus-Stroman',
    startDate: '3/16/2021',
    deadline: '4/14/2020',
    contributor: 'Arceuthobium abietinum Engelm. ex Munz ssp. abietinum',
    status: true,
    tags: 'Buick',
    requirements: '5.7.5',
    addRequirements: 'ru.ucoz.Ventosanzap',
    createdBy: 'Raviv Magrannell',
  },
  {
    id: 58,
    name: 'Layo',
    equipments: 'Treutel, Conn and Turcotte',
    startDate: '12/9/2021',
    deadline: '5/13/2020',
    contributor: 'Ivesia webberi A. Gray',
    status: true,
    tags: 'Toyota',
    requirements: '1.8',
    addRequirements: 'us.icio.Sonsing',
    createdBy: 'Mufi Churchin',
  },
  {
    id: 59,
    name: 'Wikibox',
    equipments: 'Bernier, Kuphal and Crona',
    startDate: '2/9/2022',
    deadline: '4/13/2020',
    contributor: 'Lepechinia calycina (Benth.) Epling ex Munz',
    status: false,
    tags: 'Mercedes-Benz',
    requirements: '1.6.9',
    addRequirements: 'com.prnewswire.Ronstring',
    createdBy: 'Charo Caygill',
  },
  {
    id: 60,
    name: 'Ainyx',
    equipments: 'Dickens-Crist',
    startDate: '10/16/2020',
    deadline: '10/3/2021',
    contributor: 'Veronica beccabunga L.',
    status: false,
    tags: 'Nissan',
    requirements: '0.32',
    addRequirements: 'com.sciencedaily.Sub-Ex',
    createdBy: 'Leda Twining',
  },
  {
    id: 61,
    name: 'Ainyx',
    equipments: 'Lang Group',
    startDate: '7/4/2020',
    deadline: '1/24/2021',
    contributor: 'Chionophila tweedyi (Canby & Rose) L.F. Hend.',
    status: true,
    tags: 'Nissan',
    requirements: '3.4.3',
    addRequirements: 'com.weebly.Span',
    createdBy: 'Rosalia Pirrie',
  },
  {
    id: 62,
    name: 'Jabbersphere',
    equipments: 'Lakin and Sons',
    startDate: '6/13/2021',
    deadline: '8/5/2021',
    contributor: 'Steinchisma hians (Elliott) Nash',
    status: false,
    tags: 'Lexus',
    requirements: '0.86',
    addRequirements: 'cn.com.people.Greenlam',
    createdBy: 'Gilberte Ridding',
  },
  {
    id: 63,
    name: 'Avamm',
    equipments: 'Reynolds Inc',
    startDate: '9/11/2020',
    deadline: '11/19/2020',
    contributor: 'Gahnia aspera Spreng.',
    status: true,
    tags: 'Peugeot',
    requirements: '0.8.2',
    addRequirements: 'net.furl.Fixflex',
    createdBy: 'Nata Eales',
  },
  {
    id: 64,
    name: 'Gabtype',
    equipments: 'Erdman, Kilback and Metz',
    startDate: '4/3/2020',
    deadline: '1/31/2022',
    contributor: 'Sphenopholis filiformis (Chapm.) Scribn.',
    status: true,
    tags: 'Mitsubishi',
    requirements: '7.09',
    addRequirements: 'com.shutterfly.Domainer',
    createdBy: 'Artemis Pettiford',
  },
  {
    id: 65,
    name: 'Thoughtstorm',
    equipments: 'Koss-Cartwright',
    startDate: '4/29/2021',
    deadline: '2/21/2022',
    contributor: 'Epilobium ×pulchrum Suksd. (pro sp.)',
    status: true,
    tags: 'Kia',
    requirements: '3.2.4',
    addRequirements: 'com.fotki.Aerified',
    createdBy: 'Merrie Sterling',
  },
  {
    id: 66,
    name: 'Mita',
    equipments: 'Schuster, Heller and Langworth',
    startDate: '4/12/2020',
    deadline: '5/24/2021',
    contributor: 'Lithospermum ruderale Douglas ex Lehm.',
    status: false,
    tags: 'Volkswagen',
    requirements: '8.10',
    addRequirements: 'eu.europa.Greenlam',
    createdBy: 'Margaret Gundrey',
  },
  {
    id: 67,
    name: 'Skimia',
    equipments: "Zulauf, O'Connell and Graham",
    startDate: '7/16/2021',
    deadline: '4/19/2020',
    contributor: 'Myrsine linearifolia Hosaka',
    status: false,
    tags: 'Pontiac',
    requirements: '7.6.9',
    addRequirements: 'fr.free.Zoolab',
    createdBy: 'Jacinda Leyre',
  },
  {
    id: 68,
    name: 'Mydo',
    equipments: 'Marquardt-Schaden',
    startDate: '7/30/2020',
    deadline: '8/31/2021',
    contributor: 'Typha latifolia L.',
    status: false,
    tags: 'Subaru',
    requirements: '0.18',
    addRequirements: 'com.sbwire.Wrapsafe',
    createdBy: 'Vance Mearing',
  },
  {
    id: 69,
    name: 'Dablist',
    equipments: 'Waters Group',
    startDate: '4/24/2020',
    deadline: '8/10/2020',
    contributor: 'Lagetta lagetto (Sw.) Nash',
    status: true,
    tags: 'Buick',
    requirements: '0.1.0',
    addRequirements: 'com.list-manage.It',
    createdBy: 'Randene Ullyott',
  },
  {
    id: 70,
    name: 'Thoughtstorm',
    equipments: 'Hayes-Nicolas',
    startDate: '1/2/2022',
    deadline: '10/6/2021',
    contributor: 'Gymnocarpium disjunctum (Rupr.) Ching',
    status: true,
    tags: 'Chevrolet',
    requirements: '6.74',
    addRequirements: 'com.businessweek.Sub-Ex',
    createdBy: 'Stephine Breit',
  },
  {
    id: 71,
    name: 'Yodoo',
    equipments: 'Hartmann, Lubowitz and Hirthe',
    startDate: '10/28/2021',
    deadline: '9/16/2021',
    contributor: 'Lobelia siphilitica L. var. siphilitica',
    status: true,
    tags: 'Buick',
    requirements: '0.79',
    addRequirements: 'jp.geocities.Holdlamis',
    createdBy: 'Tandie Skeech',
  },
  {
    id: 72,
    name: 'Oyoloo',
    equipments: 'Nicolas-Boyle',
    startDate: '7/5/2021',
    deadline: '9/27/2020',
    contributor: 'Juncus haenkei E. Mey.',
    status: false,
    tags: 'Buick',
    requirements: '0.3.8',
    addRequirements: 'com.diigo.Cookley',
    createdBy: 'Arden Axtell',
  },
  {
    id: 73,
    name: 'Zooveo',
    equipments: 'Padberg LLC',
    startDate: '4/24/2020',
    deadline: '10/20/2021',
    contributor: 'Pyrrocoma apargioides (A. Gray) Greene',
    status: false,
    tags: 'Ram',
    requirements: '9.5',
    addRequirements: 'com.bloglines.Solarbreeze',
    createdBy: 'Bessie Slucock',
  },
  {
    id: 74,
    name: 'Cogidoo',
    equipments: 'Schaefer-Macejkovic',
    startDate: '1/17/2021',
    deadline: '10/25/2021',
    contributor: 'Isoetes flaccida Shuttlw. ex A. Braun var. flaccida',
    status: true,
    tags: 'Isuzu',
    requirements: '0.4.3',
    addRequirements: 'com.nationalgeographic.Bytecard',
    createdBy: 'Rozina Burnel',
  },
  {
    id: 75,
    name: 'Divavu',
    equipments: 'Lind, Nolan and Moore',
    startDate: '2/5/2022',
    deadline: '11/6/2021',
    contributor: 'Microseris borealis (Bong.) Sch. Bip.',
    status: true,
    tags: 'MINI',
    requirements: '1.8',
    addRequirements: 'com.fastcompany.Keylex',
    createdBy: 'Lindi Kinnar',
  },
  {
    id: 76,
    name: 'Jabberbean',
    equipments: 'Cassin LLC',
    startDate: '2/5/2021',
    deadline: '12/28/2021',
    contributor: 'Callirhoe alcaeoides (Michx.) A. Gray',
    status: false,
    tags: 'Nissan',
    requirements: '0.2.9',
    addRequirements: 'com.tripadvisor.Namfix',
    createdBy: 'Leo Curgenven',
  },
  {
    id: 77,
    name: 'Skinder',
    equipments: 'Wilkinson, Gerlach and Kertzmann',
    startDate: '11/24/2020',
    deadline: '10/3/2021',
    contributor: 'Galium pilosum Aiton var. pilosum',
    status: false,
    tags: 'Pontiac',
    requirements: '0.6.9',
    addRequirements: 'com.sun.Aerified',
    createdBy: 'Harcourt Geyton',
  },
  {
    id: 78,
    name: 'Meeveo',
    equipments: 'Muller-Fritsch',
    startDate: '10/22/2021',
    deadline: '11/11/2020',
    contributor:
      'Plagiobothrys scouleri (Hook. & Arn.) I.M. Johnst. var. scouleri',
    status: false,
    tags: 'Chevrolet',
    requirements: '5.5.8',
    addRequirements: 'com.rediff.Bamity',
    createdBy: 'Stu Skpsey',
  },
  {
    id: 79,
    name: 'Nlounge',
    equipments: 'Schmitt, Bins and Reilly',
    startDate: '10/27/2020',
    deadline: '1/6/2021',
    contributor: 'Fraxinus greggii A. Gray',
    status: false,
    tags: 'Mercedes-Benz',
    requirements: '7.6.8',
    addRequirements: 'com.gravatar.Veribet',
    createdBy: 'Ruby Vorley',
  },
  {
    id: 80,
    name: 'Aimbo',
    equipments: 'Kub, Gusikowski and Emard',
    startDate: '5/4/2021',
    deadline: '7/4/2020',
    contributor: 'Eriogonum pharnaceoides Torr.',
    status: true,
    tags: 'Audi',
    requirements: '3.1',
    addRequirements: 'gd.is.Treeflex',
    createdBy: 'Marita Ginnane',
  },
  {
    id: 81,
    name: 'Quimba',
    equipments: 'Bartoletti, Dach and Bernhard',
    startDate: '2/6/2021',
    deadline: '12/4/2020',
    contributor: 'Ranunculus hyperboreus Rottb.',
    status: false,
    tags: 'Lincoln',
    requirements: '9.87',
    addRequirements: 'com.example.Lotstring',
    createdBy: 'Orlando Bartoszinski',
  },
  {
    id: 82,
    name: 'Devshare',
    equipments: 'Legros-Denesik',
    startDate: '6/30/2021',
    deadline: '2/19/2021',
    contributor: 'Capsicum chinense Jacq. [excluded]',
    status: false,
    tags: 'GMC',
    requirements: '8.8',
    addRequirements: 'com.skype.Mat Lam Tam',
    createdBy: 'Blake Yakov',
  },
  {
    id: 83,
    name: 'Zoovu',
    equipments: 'Cremin and Sons',
    startDate: '12/31/2021',
    deadline: '1/31/2022',
    contributor: 'Arethusa L.',
    status: false,
    tags: 'Mitsubishi',
    requirements: '0.2.2',
    addRequirements: 'com.geocities.Greenlam',
    createdBy: 'Gwyn Gritten',
  },
  {
    id: 84,
    name: 'Browsebug',
    equipments: 'Braun, Nitzsche and Abernathy',
    startDate: '11/11/2020',
    deadline: '8/6/2021',
    contributor: 'Hypericum ellipticum Hook.',
    status: false,
    tags: 'Ford',
    requirements: '9.3.4',
    addRequirements: 'fr.unblog.Keylex',
    createdBy: 'Hebert Somerbell',
  },
  {
    id: 85,
    name: 'Buzzbean',
    equipments: 'Hammes Inc',
    startDate: '2/7/2022',
    deadline: '6/21/2020',
    contributor: 'Pinus arizonica Engelm. var. stormiae Martínez',
    status: false,
    tags: 'Fairthorpe',
    requirements: '0.75',
    addRequirements: 'ca.cbc.Overhold',
    createdBy: 'Nelia St. Quentin',
  },
  {
    id: 86,
    name: 'Twiyo',
    equipments: 'Lueilwitz Inc',
    startDate: '10/3/2021',
    deadline: '4/10/2021',
    contributor: 'Phlox drummondii Hook. ssp. mcallisteri (Whitehouse) Wherry',
    status: false,
    tags: 'Mazda',
    requirements: '0.3.8',
    addRequirements: 'com.multiply.Transcof',
    createdBy: 'Neille Rockhall',
  },
  {
    id: 87,
    name: 'Thoughtstorm',
    equipments: 'Rowe LLC',
    startDate: '11/12/2021',
    deadline: '8/16/2020',
    contributor: 'Arthonia albovirescens Nyl.',
    status: true,
    tags: 'Saab',
    requirements: '0.5.9',
    addRequirements: 'com.shinystat.Rank',
    createdBy: 'Delano Peet',
  },
  {
    id: 88,
    name: 'Thoughtbeat',
    equipments: 'Lockman-Price',
    startDate: '2/17/2022',
    deadline: '4/3/2021',
    contributor:
      'Silene campanulata S. Watson ssp. glandulosa C.L. Hitchc. & Maguire',
    status: false,
    tags: 'Buick',
    requirements: '6.3',
    addRequirements: 'com.twitter.Cardguard',
    createdBy: 'Lou Wickrath',
  },
  {
    id: 89,
    name: 'Avavee',
    equipments: 'Baumbach-Considine',
    startDate: '12/12/2021',
    deadline: '2/5/2021',
    contributor: 'Trypethelium mastoideum (Ach.) Ach.',
    status: false,
    tags: 'Oldsmobile',
    requirements: '1.75',
    addRequirements: 'com.cbsnews.Subin',
    createdBy: 'Nonie Rigmond',
  },
  {
    id: 90,
    name: 'BlogXS',
    equipments: 'Erdman and Sons',
    startDate: '4/21/2020',
    deadline: '6/8/2021',
    contributor: 'Cyrtandra ×hosakae H. St. John & Storey (pro sp.)',
    status: false,
    tags: 'Nissan',
    requirements: '2.7',
    addRequirements: 'com.mozilla.Cardguard',
    createdBy: 'Reider Naper',
  },
  {
    id: 91,
    name: 'Lazzy',
    equipments: 'Kuvalis-Haag',
    startDate: '5/13/2021',
    deadline: '8/22/2020',
    contributor: 'Gentianopsis simplex (A. Gray) Iltis',
    status: true,
    tags: 'Volvo',
    requirements: '0.15',
    addRequirements: 'com.github.Wrapsafe',
    createdBy: 'Ramsey Bareford',
  },
  {
    id: 92,
    name: 'Jayo',
    equipments: 'Lang Inc',
    startDate: '6/26/2021',
    deadline: '2/9/2022',
    contributor: 'Caragana arborescens Lam.',
    status: true,
    tags: 'Land Rover',
    requirements: '0.4.8',
    addRequirements: 'com.list-manage.Bytecard',
    createdBy: 'Carr Georges',
  },
  {
    id: 93,
    name: 'Pixoboo',
    equipments: 'Abernathy, Blick and Glover',
    startDate: '6/10/2020',
    deadline: '11/30/2020',
    contributor: 'Polemonium boreale M.F. Adams',
    status: false,
    tags: 'Mercedes-Benz',
    requirements: '6.1',
    addRequirements: 'me.flavors.Zontrax',
    createdBy: 'Nathalie Hewson',
  },
  {
    id: 94,
    name: 'Dynazzy',
    equipments: 'McDermott, Aufderhar and Kohler',
    startDate: '7/26/2020',
    deadline: '12/9/2020',
    contributor: 'Gypsoplaca macrophylla (Zahlbr.) Timdal',
    status: false,
    tags: 'Hummer',
    requirements: '0.9.0',
    addRequirements: 'com.typepad.Regrant',
    createdBy: 'Queenie Hartgill',
  },
  {
    id: 95,
    name: 'Meemm',
    equipments: 'Douglas Inc',
    startDate: '6/5/2021',
    deadline: '9/27/2021',
    contributor: 'Crotalaria assamica Benth.',
    status: false,
    tags: 'Chevrolet',
    requirements: '0.5.3',
    addRequirements: 'edu.berkeley.Bitchip',
    createdBy: 'Vilhelmina Strickland',
  },
  {
    id: 96,
    name: 'Skinte',
    equipments: 'Kling, Torphy and Huels',
    startDate: '8/4/2020',
    deadline: '7/12/2020',
    contributor: 'Arthonia luridoalba Nyl.',
    status: true,
    tags: 'Ford',
    requirements: '0.3.7',
    addRequirements: 'com.csmonitor.Fixflex',
    createdBy: 'Kimble Kamien',
  },
  {
    id: 97,
    name: 'Skyvu',
    equipments: 'Rogahn Group',
    startDate: '8/23/2020',
    deadline: '11/30/2020',
    contributor: 'Cleyera japonica Thunb.',
    status: true,
    tags: 'BMW',
    requirements: '7.53',
    addRequirements: 'com.ycombinator.Tresom',
    createdBy: 'Jeralee Geeson',
  },
  {
    id: 98,
    name: 'Ntag',
    equipments: 'Berge, Hessel and Haag',
    startDate: '1/8/2021',
    deadline: '11/9/2021',
    contributor: 'Trichosanthes anguina L.',
    status: false,
    tags: 'Nissan',
    requirements: '0.9.4',
    addRequirements: 'org.bbb.Trippledex',
    createdBy: 'Archibald Worrill',
  },
  {
    id: 99,
    name: 'Quatz',
    equipments: 'Stroman and Sons',
    startDate: '6/15/2020',
    deadline: '3/31/2021',
    contributor: 'Kohlmeyera Schatz',
    status: true,
    tags: 'Volkswagen',
    requirements: '0.59',
    addRequirements: 'com.discovery.Fixflex',
    createdBy: 'Lenci Meigh',
  },
  {
    id: 100,
    name: 'Edgewire',
    equipments: 'Gorczany, Tillman and Roob',
    startDate: '2/10/2022',
    deadline: '1/9/2021',
    contributor: 'Punica L.',
    status: false,
    tags: 'Mazda',
    requirements: '3.6.5',
    addRequirements: 'com.nydailynews.Bigtax',
    createdBy: 'Rufe Eadmeads',
  },
];
