import { DataGrid } from '@mui/x-data-grid';
import React, { useEffect, useState } from 'react';
import CustomToolbar from '../shared/CustomToolbar';

const columns = [
  { field: 'name', headerName: 'Analysis Created By', width: 200 },
  { field: 'createdBy', headerName: 'Lab', width: 150 },
  { field: 'equipments', headerName: 'Project', width: 150 },
  { field: 'startDate', headerName: 'Name', width: 150 },
  { field: 'deadline', headerName: 'Equipment', width: 150 },
  { field: 'description', headerName: 'Description', width: 150 },
  { field: 'contributor', headerName: 'Contributor', width: 150 },
  { field: 'status', headerName: 'Visibility', width: 150 },
  {
    headerName: 'Actions',

    width: 200,
    renderCell: ({ row }) => {
      const { status } = row;
      return (
        <div className='flex gap-x-1'>
          <button className='bg-sky-600 text-white px-2 py-1 rounded'>
            Edit
          </button>
          {status ? (
            <button className='bg-green-500 text-white px-2 py-1 rounded'>
              Active
            </button>
          ) : (
            <button className='bg-indigo-900 text-white px-2 py-1 rounded'>
              Inactive
            </button>
          )}

          <button className='bg-red-500 text-white px-2 py-1 rounded'>
            Delete
          </button>
        </div>
      );
    },
  },
];

const Table = () => {
  const [pageSize, setPageSize] = React.useState(10);
  const [data, setData] = useState([]);
  const [filterData, setFilterData] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  useEffect(() => {
    setData(allData);
    setFilterData(allData);
  }, []);
  useEffect(() => {
    const columnsProps = [
      'name',
      'createdBy',
      'equipments',
      'startDate',
      'deadline',
      'description',
      'contributor',
    ];
    const filterData = () => {
      const filterIds = columnsProps
        .map((col) => {
          const colWiseData = data.map((item) => {
            return { id: item.id, data: item[col], col };
          });
          const searchItem = colWiseData
            .filter((item) => {
              if (
                item.data
                  .toLowerCase()
                  .includes(searchTerm.trim().toLowerCase())
              ) {
                return true;
              }
              return false;
            })
            .map((item) => item.id);
          return searchItem;
        })
        .flat(Infinity);
      const uniqueFilterIdes = Array.from(new Set([...filterIds]));
      const filterItems = data.filter((item) =>
        uniqueFilterIdes.includes(item.id)
      );

      return filterItems;
    };

    setFilterData(filterData());
    return () => filterData();
  }, [searchTerm, data]);
  const searchTermOnChange = (event) => {
    if (event.target.value !== searchTerm) {
      setSearchTerm(event.target.value);
    }
  };
  return (
    <div
      style={{ height: data.length > 0 ? 700 : 220, width: '100%' }}
      className='mt-5'
    >
      <DataGrid
        rows={filterData}
        columns={columns}
        disableSelectionOnClick
        disableColumnMenu
        pageSize={pageSize}
        onPageSizeChange={(newPageSize) => setPageSize(newPageSize)}
        rowsPerPageOptions={[10, 20, 30, 50]}
        pagination
        components={{ Toolbar: CustomToolbar }}
        componentsProps={{
          toolbar: { data, columns, searchTerm, onChange: searchTermOnChange },
        }}
        style={{ border: 'none' }}
      />
    </div>
  );
};

export default Table;

const allData = [
  {
    id: 1,
    name: 'Malanie Gwin',
    createdBy: 'Brown Inc',
    equipments: 'Beaver, european',
    startDate: '20/08/2020',
    deadline: '25/03/2020',
    description: 'Anal low risk human papillomavirus (HPV) DNA test positive',
    contributor: 'Torphy and Sons',
    status: true,
  },
  {
    id: 2,
    name: 'Bea Wille',
    createdBy: 'Sporer LLC',
    equipments: 'Paca',
    startDate: '29/06/2021',
    deadline: '02/06/2021',
    description: 'Post-traumatic anterior urethral stricture',
    contributor: 'Hand, Swaniawski and Swaniawski',
    status: true,
  },
  {
    id: 3,
    name: 'Nanette Fagence',
    createdBy: 'Ferry, Quigley and Rohan',
    equipments: 'Gulls (unidentified)',
    startDate: '17/08/2021',
    deadline: '18/02/2020',
    description: 'Congenital occlusion of ureteropelvic junction',
    contributor: 'Dietrich-Bashirian',
    status: false,
  },
  {
    id: 4,
    name: 'Sancho Fenty',
    createdBy: 'Kessler LLC',
    equipments: 'Cormorant, great',
    startDate: '06/03/2021',
    deadline: '05/03/2021',
    description: 'Open bite of other specified part of neck',
    contributor: 'Ryan Inc',
    status: true,
  },
  {
    id: 5,
    name: 'Ronny Picott',
    createdBy: 'Towne Inc',
    equipments: 'Shelduck, european',
    startDate: '10/09/2020',
    deadline: '18/08/2021',
    description: 'Disp fx of lateral condyle of l tibia, 7thE',
    contributor: 'Bins-Kozey',
    status: false,
  },
  {
    id: 6,
    name: 'Retha Scopham',
    createdBy: 'Swaniawski-Beahan',
    equipments: 'Mocking cliffchat',
    startDate: '19/01/2021',
    deadline: '14/02/2021',
    description: 'Pnctr w fb of unsp eyelid and periocular area, init',
    contributor: 'Rempel-Johns',
    status: false,
  },
  {
    id: 7,
    name: 'Laurie Phizackarley',
    createdBy: 'Gibson, Hermiston and Rath',
    equipments: 'African pied wagtail',
    startDate: '06/02/2022',
    deadline: '06/04/2021',
    description: 'Burn of third degree of unspecified upper arm',
    contributor: 'Beahan-Orn',
    status: true,
  },
  {
    id: 8,
    name: 'Crawford Wolfer',
    createdBy: 'Zemlak LLC',
    equipments: 'Cat, european wild',
    startDate: '30/05/2020',
    deadline: '02/12/2020',
    description: 'Oth fx lower end of r tibia, subs for clos fx w routn heal',
    contributor: 'Bogan, Doyle and Effertz',
    status: true,
  },
  {
    id: 9,
    name: 'Edik Round',
    createdBy: 'Kautzer-Tillman',
    equipments: 'Praying mantis (unidentified)',
    startDate: '23/02/2021',
    deadline: '15/03/2021',
    description: 'Activity, golf',
    contributor: 'Ankunding Group',
    status: true,
  },
  {
    id: 10,
    name: 'Sal Bobasch',
    createdBy: 'Hodkiewicz, Gleason and Gottlieb',
    equipments: 'Red phalarope',
    startDate: '01/07/2021',
    deadline: '19/12/2020',
    description: 'Poisoning by unsp systemic antibiotic, self-harm, sequela',
    contributor: 'Christiansen, Lind and Crooks',
    status: true,
  },
  {
    id: 11,
    name: 'Tuck Pickworth',
    createdBy: 'West, Gaylord and Kuhic',
    equipments: 'Neotropic cormorant',
    startDate: '05/01/2021',
    deadline: '29/10/2020',
    description: 'Nondisp fx of distal pole of navic bone of unsp wrist, sqla',
    contributor: 'Lubowitz, Ebert and Barrows',
    status: true,
  },
  {
    id: 12,
    name: 'Fanny Hannaford',
    createdBy: 'Jerde Inc',
    equipments: 'Andean goose',
    startDate: '31/08/2021',
    deadline: '27/11/2019',
    description: 'Chronic or unspecified gastrojejunal ulcer with hemorrhage',
    contributor: 'Davis, Wolf and Schuppe',
    status: true,
  },
  {
    id: 13,
    name: 'Salvador Desaur',
    createdBy: 'Beier-Kuvalis',
    equipments: 'Colobus, black and white',
    startDate: '27/09/2020',
    deadline: '05/02/2020',
    description: 'Predominantly alpha-adrenoreceptor agonists',
    contributor: 'Ebert-Langworth',
    status: false,
  },
  {
    id: 14,
    name: 'Marielle Potteridge',
    createdBy: 'Kohler-Rogahn',
    equipments: 'Red-necked phalarope',
    startDate: '01/04/2020',
    deadline: '16/11/2021',
    description: 'Herpesviral infection, unspecified',
    contributor: 'Casper Group',
    status: true,
  },
  {
    id: 15,
    name: 'Hermina Brinded',
    createdBy: 'Wilkinson, Padberg and Kreiger',
    equipments: 'Black-footed ferret',
    startDate: '24/10/2020',
    deadline: '08/12/2021',
    description: 'Unsp superficial injuries of right back wall of thorax, init',
    contributor: 'Fritsch-Weissnat',
    status: false,
  },
  {
    id: 16,
    name: 'Jourdan Rosling',
    createdBy: 'Stiedemann-Goodwin',
    equipments: 'Short-beaked echidna',
    startDate: '18/05/2020',
    deadline: '28/10/2021',
    description: 'Contusion of lung, bilateral, sequela',
    contributor: 'Hermann, Marks and Turner',
    status: false,
  },
  {
    id: 17,
    name: 'Allyson Loweth',
    createdBy: 'Wisozk-Hauck',
    equipments: 'Toucan, red-billed',
    startDate: '16/07/2021',
    deadline: '28/11/2020',
    description: 'Leakage of surgically created arteriovenous shunt, subs',
    contributor: 'Dach Group',
    status: false,
  },
  {
    id: 18,
    name: 'Nelly Ianni',
    createdBy: 'Hilll, Kertzmann and Bins',
    equipments: 'Blue and yellow macaw',
    startDate: '23/09/2021',
    deadline: '29/06/2020',
    description: 'Fx unsp prt of nk of unsp femr, 7thQ',
    contributor: 'Rowe LLC',
    status: false,
  },
  {
    id: 19,
    name: 'Konstance Marchiso',
    createdBy: 'Stroman and Sons',
    equipments: 'Ring-tailed possum',
    startDate: '14/03/2021',
    deadline: '28/08/2021',
    description: 'Open bite of l frnt wl of thorax w penet thor cavity, sqla',
    contributor: 'Sipes-Heaney',
    status: false,
  },
  {
    id: 20,
    name: 'Lilli Chart',
    createdBy: 'Cummerata-Heidenreich',
    equipments: 'Grenadier, purple',
    startDate: '09/11/2020',
    deadline: '01/02/2022',
    description: 'Laceration of unsp kidney, unspecified degree, init encntr',
    contributor: 'Oberbrunner-Johnson',
    status: false,
  },
  {
    id: 21,
    name: 'Tammy Beauly',
    createdBy: 'Boyle Inc',
    equipments: 'Wallaby, whip-tailed',
    startDate: '24/09/2020',
    deadline: '31/10/2021',
    description: 'Adverse effect of unsp antipsychotics and neuroleptics',
    contributor: 'Adams-Crist',
    status: true,
  },
  {
    id: 22,
    name: 'Monroe Ropking',
    createdBy: 'Schuppe, Sauer and Franecki',
    equipments: 'Common mynah',
    startDate: '16/01/2022',
    deadline: '08/02/2021',
    description: 'Loose body in left shoulder',
    contributor: 'Larkin, Mayert and Leuschke',
    status: true,
  },
  {
    id: 23,
    name: 'Burt Farnes',
    createdBy: 'Waters, Funk and Gottlieb',
    equipments: 'Saddle-billed stork',
    startDate: '06/03/2021',
    deadline: '27/08/2020',
    description: 'Pupillary membranes, unspecified eye',
    contributor: 'Ziemann, McClure and Little',
    status: false,
  },
  {
    id: 24,
    name: 'Katey Nozzolii',
    createdBy: 'Bradtke Group',
    equipments: 'Cormorant, pied',
    startDate: '22/09/2020',
    deadline: '25/11/2019',
    description: 'Partial traumatic amp at level betw right hip and knee, init',
    contributor: 'Wiegand, Gaylord and Kuhlman',
    status: false,
  },
  {
    id: 25,
    name: 'Donnajean Morston',
    createdBy: 'Kertzmann and Sons',
    equipments: 'Black-tailed tree creeper',
    startDate: '13/11/2020',
    deadline: '25/07/2020',
    description: 'Displ oblique fx shaft of unsp ulna, 7thH',
    contributor: 'Gerlach, Dietrich and Gutkowski',
    status: true,
  },
  {
    id: 26,
    name: 'Celisse Ewbanche',
    createdBy: 'Christiansen-Rutherford',
    equipments: 'Common duiker',
    startDate: '28/12/2020',
    deadline: '03/04/2020',
    description: 'Nondisp commnt fx shaft of rad, l arm, 7thK',
    contributor: 'Dare and Sons',
    status: true,
  },
  {
    id: 27,
    name: 'Hy Newns',
    createdBy: 'Jakubowski-Kuvalis',
    equipments: 'Bohor reedbuck',
    startDate: '27/10/2021',
    deadline: '11/06/2021',
    description: 'Nondisp commnt fx shaft of unsp fibula, 7thN',
    contributor: 'Hirthe, Kuhlman and Cartwright',
    status: true,
  },
  {
    id: 28,
    name: 'Charlton Onslow',
    createdBy: 'Hagenes-Will',
    equipments: 'Grey phalarope',
    startDate: '13/04/2021',
    deadline: '26/01/2020',
    description: 'Unsp inj unsp blood vess at wrs/hnd lv of right arm, sequela',
    contributor: 'Bartell and Sons',
    status: true,
  },
  {
    id: 29,
    name: 'Noah Hatry',
    createdBy: 'Towne and Sons',
    equipments: 'Lizard, collared',
    startDate: '27/12/2021',
    deadline: '15/02/2020',
    description: 'Laceration of lip and oral cavity without foreign body',
    contributor: 'Moore, Glover and Strosin',
    status: false,
  },
  {
    id: 30,
    name: 'Valerie Raiker',
    createdBy: 'Emard Group',
    equipments: 'Red sheep',
    startDate: '19/11/2021',
    deadline: '15/01/2022',
    description: 'Dracunculiasis',
    contributor: 'Dare-Kuhlman',
    status: false,
  },
  {
    id: 31,
    name: 'Lorrie Regglar',
    createdBy: 'Williamson and Sons',
    equipments: 'Sunbird, lesser double-collared',
    startDate: '25/01/2021',
    deadline: '23/01/2021',
    description: 'Nondisp apophyseal fx l femur, init for opn fx type 3A/B/C',
    contributor: 'Doyle-Lehner',
    status: true,
  },
  {
    id: 32,
    name: 'Yancey Rumbellow',
    createdBy: 'Swaniawski, Pollich and Schamberger',
    equipments: 'Capuchin, weeper',
    startDate: '09/03/2021',
    deadline: '02/10/2020',
    description: 'Acc pnctr & lac of a ms structure during oth procedure',
    contributor: 'Jacobson, Beier and Farrell',
    status: false,
  },
  {
    id: 33,
    name: 'Pamella Lorant',
    createdBy: 'Spinka LLC',
    equipments: 'Indian giant squirrel',
    startDate: '24/02/2021',
    deadline: '05/12/2019',
    description: 'Other rupture of muscle (nontraumatic), unspecified thigh',
    contributor: 'Considine-Gleichner',
    status: false,
  },
  {
    id: 34,
    name: 'Cliff Stiffkins',
    createdBy: 'Bahringer, Batz and Klein',
    equipments: 'Black-backed jackal',
    startDate: '15/05/2020',
    deadline: '24/06/2021',
    description: 'Acute graft-versus-host disease',
    contributor: 'Hessel-Will',
    status: false,
  },
  {
    id: 35,
    name: 'Ree Bielby',
    createdBy: 'Bauch, Schuster and Robel',
    equipments: 'Common duiker',
    startDate: '16/12/2020',
    deadline: '31/03/2021',
    description: 'Oth disrd of bone density and structure, other site',
    contributor: 'Wyman Inc',
    status: true,
  },
  {
    id: 36,
    name: 'Sibylle Aymes',
    createdBy: 'Lindgren, Connelly and Dooley',
    equipments: 'Red brocket',
    startDate: '01/12/2020',
    deadline: '08/09/2020',
    description: 'Injury of tibial nerve at lower leg level, unsp leg, subs',
    contributor: "O'Keefe-Bernhard",
    status: false,
  },
  {
    id: 37,
    name: 'Calvin Pietrowicz',
    createdBy: 'Runolfsson, Yost and Roberts',
    equipments: 'Fox, asian red',
    startDate: '23/10/2020',
    deadline: '16/11/2020',
    description: 'Contusion of left index finger w/o damage to nail, subs',
    contributor: 'Nader-Kohler',
    status: true,
  },
  {
    id: 38,
    name: 'Gayla Olcot',
    createdBy: "O'Keefe Inc",
    equipments: 'Elephant, african',
    startDate: '21/01/2022',
    deadline: '09/05/2020',
    description: 'Foreign body granuloma of soft tissue, NEC, right forearm',
    contributor: 'Lebsack, Padberg and Fahey',
    status: false,
  },
  {
    id: 39,
    name: 'Duncan Turton',
    createdBy: 'Wolff LLC',
    equipments: 'Lizard, giant girdled',
    startDate: '16/06/2021',
    deadline: '06/08/2021',
    description: 'Burn of unspecified degree of back of unspecified hand',
    contributor: 'Boehm, Nienow and Blanda',
    status: true,
  },
  {
    id: 40,
    name: 'Nikaniki Barles',
    createdBy: 'VonRueden, Blanda and Corwin',
    equipments: "Grant's gazelle",
    startDate: '22/05/2021',
    deadline: '18/06/2021',
    description: 'Disp fx of med cuneiform of l foot, subs for fx w routn heal',
    contributor: 'Zieme, Gusikowski and Stehr',
    status: false,
  },
  {
    id: 41,
    name: 'Eustacia Ennals',
    createdBy: 'Moen Group',
    equipments: 'Grey phalarope',
    startDate: '30/11/2021',
    deadline: '19/07/2020',
    description: 'Neoplasm of uncertain behavior of oth female genital organs',
    contributor: 'Lindgren, Bergnaum and Wisozk',
    status: true,
  },
  {
    id: 42,
    name: 'Tirrell Mulbry',
    createdBy: 'Stracke Group',
    equipments: 'Eleven-banded armadillo (unidentified)',
    startDate: '27/12/2020',
    deadline: '28/08/2020',
    description: 'Type 1 fracture of sacrum, subs for fx w nonunion',
    contributor: 'Champlin-Wiegand',
    status: true,
  },
  {
    id: 43,
    name: 'Damaris Curnnok',
    createdBy: 'Wehner, Nienow and Reichel',
    equipments: 'Green-backed heron',
    startDate: '17/10/2020',
    deadline: '09/10/2021',
    description: 'Poisn by predom alpha-adrenocpt agonists, self-harm, subs',
    contributor: 'Cummings and Sons',
    status: true,
  },
  {
    id: 44,
    name: 'Lynnelle Capper',
    createdBy: 'Wolf Inc',
    equipments: "Zorro, azara's",
    startDate: '01/05/2021',
    deadline: '09/08/2021',
    description: 'Crushing injury of right forearm, initial encounter',
    contributor: 'Friesen-Bauch',
    status: false,
  },
  {
    id: 45,
    name: 'Mikkel Arendsen',
    createdBy: 'Bechtelar, Wolf and Labadie',
    equipments: 'Rose-ringed parakeet',
    startDate: '23/08/2021',
    deadline: '16/08/2021',
    description: 'Benign neoplasm of pancreas',
    contributor: 'Schultz-Wisozk',
    status: true,
  },
  {
    id: 46,
    name: 'Hughie Magor',
    createdBy: 'Bauch-Barrows',
    equipments: 'Hyena, striped',
    startDate: '16/10/2021',
    deadline: '19/12/2019',
    description: 'Personal history of infections of the central nervous system',
    contributor: 'Beatty, Goyette and Wilkinson',
    status: false,
  },
  {
    id: 47,
    name: 'Mallory Lifton',
    createdBy: 'Connelly, Renner and Beahan',
    equipments: 'Mynah, indian',
    startDate: '31/03/2020',
    deadline: '29/06/2020',
    description: 'Disp fx of greater trochanter of unsp femr, 7thK',
    contributor: 'Lueilwitz-Stracke',
    status: false,
  },
  {
    id: 48,
    name: 'Antonio Gariff',
    createdBy: 'Schimmel, Lebsack and Hilpert',
    equipments: 'Eagle, bateleur',
    startDate: '29/05/2020',
    deadline: '03/02/2022',
    description: 'Occup of bus injured in nonclsn trnsp acc in traf, sequela',
    contributor: 'Kub Inc',
    status: true,
  },
  {
    id: 49,
    name: 'Querida Smeal',
    createdBy: 'Schultz Group',
    equipments: 'Barrows goldeneye',
    startDate: '20/09/2021',
    deadline: '29/12/2019',
    description: 'Incomplete lesion of L5 level of lumbar spinal cord, init',
    contributor: 'Cassin-Lesch',
    status: false,
  },
  {
    id: 50,
    name: 'Odele Pembry',
    createdBy: 'Dibbert, Schmitt and Gerlach',
    equipments: 'Heron, little',
    startDate: '23/06/2020',
    deadline: '19/06/2020',
    description: 'Idiopathic chronic gout, unspecified site, without tophus',
    contributor: 'Ullrich, Corwin and Collins',
    status: false,
  },
  {
    id: 51,
    name: 'Cherianne Elders',
    createdBy: 'McLaughlin Group',
    equipments: 'Hudsonian godwit',
    startDate: '05/04/2021',
    deadline: '23/12/2019',
    description: 'Laceration of unsp kidney, unspecified degree, sequela',
    contributor: "O'Connell, Wilderman and Feil",
    status: false,
  },
  {
    id: 52,
    name: 'Kalindi Picken',
    createdBy: 'Price and Sons',
    equipments: 'Silver gull',
    startDate: '30/06/2021',
    deadline: '04/08/2021',
    description: 'Dislocation of sacroiliac and sacrococcygeal joint, sequela',
    contributor: 'Schulist-Herman',
    status: true,
  },
  {
    id: 53,
    name: 'Thea Gipson',
    createdBy: 'Corwin LLC',
    equipments: 'American black bear',
    startDate: '30/12/2020',
    deadline: '04/02/2021',
    description: 'Burn and corrosion, body region unspecified',
    contributor: 'Bradtke Group',
    status: true,
  },
  {
    id: 54,
    name: 'Thorny Hartland',
    createdBy: 'Hand-Parisian',
    equipments: 'Fox, grey',
    startDate: '20/10/2020',
    deadline: '25/07/2021',
    description: 'Strain of msl/tnd lng extensor muscle of toe at ank/ft level',
    contributor: 'Fadel, Abernathy and Romaguera',
    status: false,
  },
  {
    id: 55,
    name: 'Lisle Soaper',
    createdBy: 'Walker-Maggio',
    equipments: 'Little brown dove',
    startDate: '14/04/2021',
    deadline: '17/07/2021',
    description: 'Helicopter fire injuring occupant, initial encounter',
    contributor: 'Morar Inc',
    status: true,
  },
  {
    id: 56,
    name: 'Adelaida Petrenko',
    createdBy: 'Terry, Stracke and McClure',
    equipments: 'White-tailed jackrabbit',
    startDate: '03/01/2022',
    deadline: '28/01/2022',
    description: 'Chignon (from vacuum extraction) due to birth injury',
    contributor: 'Kovacek-Raynor',
    status: true,
  },
  {
    id: 57,
    name: 'Darb Heinle',
    createdBy: 'Schuppe-Dibbert',
    equipments: 'White-browed sparrow weaver',
    startDate: '23/06/2020',
    deadline: '30/12/2021',
    description: 'Gastric contents in pharynx causing asphyxiation, subs',
    contributor: 'Rippin-Yundt',
    status: false,
  },
  {
    id: 58,
    name: 'Ali Woodnutt',
    createdBy: 'Bernhard Group',
    equipments: 'Pine squirrel',
    startDate: '01/05/2020',
    deadline: '21/03/2021',
    description: 'Unrepairable overhanging of dental restorative materials',
    contributor: 'Mitchell, Leannon and Padberg',
    status: false,
  },
  {
    id: 59,
    name: 'Vicki Tomowicz',
    createdBy: 'Hartmann-Raynor',
    equipments: 'Falcon, prairie',
    startDate: '02/05/2021',
    deadline: '17/07/2021',
    description: 'Displ transverse fx shaft of r tibia, 7thJ',
    contributor: 'Littel, Schinner and Beier',
    status: true,
  },
  {
    id: 60,
    name: 'Banky Burrill',
    createdBy: 'Konopelski-Rempel',
    equipments: 'Lizard, blue-tongued',
    startDate: '28/10/2020',
    deadline: '29/03/2021',
    description: 'Laryngeal spasm',
    contributor: "O'Reilly-Stehr",
    status: true,
  },
  {
    id: 61,
    name: 'Bonny Kiessel',
    createdBy: 'Shields, Gutkowski and Ortiz',
    equipments: 'Bateleur eagle',
    startDate: '02/06/2020',
    deadline: '25/02/2022',
    description: 'Nondisp spiral fx shaft of r femr, 7thP',
    contributor: 'Harvey Inc',
    status: false,
  },
  {
    id: 62,
    name: "Wylma O'Sheeryne",
    createdBy: 'Cummings and Sons',
    equipments: 'South African hedgehog',
    startDate: '06/06/2020',
    deadline: '04/01/2022',
    description: 'Unsp disp fx of surg nk of unsp humer, 7thK',
    contributor: 'Leannon Inc',
    status: true,
  },
  {
    id: 63,
    name: 'Lorne Saer',
    createdBy: 'Kiehn Inc',
    equipments: 'Indian red admiral',
    startDate: '17/08/2021',
    deadline: '14/08/2021',
    description: 'Other contact with chicken, initial encounter',
    contributor: 'Carter and Sons',
    status: true,
  },
  {
    id: 64,
    name: 'Nevsa Castagne',
    createdBy: 'Reinger, Marquardt and Auer',
    equipments: 'Hyena, striped',
    startDate: '16/08/2020',
    deadline: '05/09/2020',
    description: 'Poisoning by oth parasympath, accidental, init',
    contributor: "Macejkovic, O'Hara and Gerhold",
    status: false,
  },
  {
    id: 65,
    name: 'Tadeo Affleck',
    createdBy: 'Fisher Group',
    equipments: 'Bee-eater (unidentified)',
    startDate: '06/06/2020',
    deadline: '19/07/2021',
    description: 'Other reactive arthropathies, left hand',
    contributor: 'Schroeder-VonRueden',
    status: false,
  },
  {
    id: 66,
    name: 'Flossi Brockhurst',
    createdBy: 'Goodwin, Hermann and Ritchie',
    equipments: 'Eagle, bateleur',
    startDate: '25/12/2020',
    deadline: '08/02/2022',
    description: 'Vertiginous syndromes in diseases classd elswhr, unsp ear',
    contributor: 'Rowe, Cartwright and Daugherty',
    status: true,
  },
  {
    id: 67,
    name: 'Bekki Crozier',
    createdBy: 'Trantow-Pollich',
    equipments: 'Spectacled caiman',
    startDate: '27/11/2021',
    deadline: '09/08/2021',
    description: 'War op w fragmt of improv explosv device, civilian, init',
    contributor: 'Hettinger LLC',
    status: false,
  },
  {
    id: 68,
    name: 'Benjie Izatt',
    createdBy: 'Reinger LLC',
    equipments: 'Crab, red lava',
    startDate: '27/09/2020',
    deadline: '30/03/2021',
    description: 'Reactive attachment disorder of childhood',
    contributor: 'Stroman, Christiansen and Boyle',
    status: false,
  },
  {
    id: 69,
    name: 'Vasili Leele',
    createdBy: 'Wintheiser-Raynor',
    equipments: 'Paradoxure',
    startDate: '20/11/2021',
    deadline: '17/03/2020',
    description: 'Unstable burst fracture of second lumbar vertebra, init',
    contributor: 'Hyatt and Sons',
    status: false,
  },
  {
    id: 70,
    name: 'Zelda Dowsett',
    createdBy: 'Schmidt, Simonis and Haag',
    equipments: 'Little grebe',
    startDate: '23/05/2021',
    deadline: '22/05/2021',
    description: 'Injury of unsp muscles, fascia and tendons at thigh level',
    contributor: 'Will Group',
    status: true,
  },
  {
    id: 71,
    name: 'Dewey McNickle',
    createdBy: 'Gleason, Sanford and Walter',
    equipments: 'Sloth, two-toed tree',
    startDate: '02/05/2020',
    deadline: '16/01/2021',
    description: 'Central dislocation of right hip',
    contributor: 'Greenholt, Welch and Wyman',
    status: false,
  },
  {
    id: 72,
    name: 'Henderson Copland',
    createdBy: 'Hettinger LLC',
    equipments: 'Otter, small-clawed',
    startDate: '16/05/2020',
    deadline: '28/05/2020',
    description: 'Nondisp commnt fx shaft of l tibia, 7thR',
    contributor: 'Wilderman-Murray',
    status: true,
  },
  {
    id: 73,
    name: 'Derrick Lethcoe',
    createdBy: 'Hane, Kuhn and Wehner',
    equipments: 'American crow',
    startDate: '16/12/2021',
    deadline: '13/03/2021',
    description: 'Cholesteatoma of middle ear',
    contributor: "Jones, O'Reilly and Wilderman",
    status: false,
  },
  {
    id: 74,
    name: 'Diana Meredith',
    createdBy: 'Hoppe, Windler and Langosh',
    equipments: 'Civet, small-toothed palm',
    startDate: '14/01/2021',
    deadline: '28/08/2021',
    description: 'Nondisp suprcndl fx w intrcndl extn low end r femr, 7thD',
    contributor: 'Runolfsson-Padberg',
    status: false,
  },
  {
    id: 75,
    name: 'Rene Chrishop',
    createdBy: 'McGlynn, Cassin and Jaskolski',
    equipments: 'Beaver, american',
    startDate: '22/10/2020',
    deadline: '29/11/2021',
    description: 'Tox eff of nitrodrv/aminodrv of benzn/homolog, slf-hrm, init',
    contributor: 'Dietrich-Hirthe',
    status: false,
  },
  {
    id: 76,
    name: 'Lira Mishow',
    createdBy: 'Romaguera, Champlin and Torphy',
    equipments: 'Osprey',
    startDate: '07/02/2022',
    deadline: '27/02/2020',
    description: 'Varicose veins of lower extremities',
    contributor: 'Hilpert-Schaefer',
    status: true,
  },
  {
    id: 77,
    name: 'Allene Cunah',
    createdBy: 'Pollich, Keebler and Mertz',
    equipments: 'Dog, black-tailed prairie',
    startDate: '13/06/2020',
    deadline: '02/01/2021',
    description: 'Driver of pk-up/van injured in clsn w unsp mv in traf, init',
    contributor: 'Beahan, Lemke and Boehm',
    status: true,
  },
  {
    id: 78,
    name: 'Cassey Mewett',
    createdBy: 'Leffler Group',
    equipments: 'Yellow-billed stork',
    startDate: '08/04/2021',
    deadline: '17/05/2021',
    description: 'Drown due to fall off fishing boat, sequela',
    contributor: 'Ward Group',
    status: true,
  },
  {
    id: 79,
    name: 'Jeannette Fellos',
    createdBy: 'Osinski and Sons',
    equipments: 'Roseat flamingo',
    startDate: '10/05/2021',
    deadline: '03/08/2021',
    description: 'Item causing external constriction',
    contributor: 'Hayes-Schinner',
    status: false,
  },
  {
    id: 80,
    name: 'Clyde Silversmidt',
    createdBy: 'Gislason-Thiel',
    equipments: 'Duck, white-faced whistling',
    startDate: '04/11/2021',
    deadline: '28/11/2019',
    description: 'Other endosseous dental implant failure',
    contributor: 'Wyman, Rodriguez and Lockman',
    status: true,
  },
  {
    id: 81,
    name: 'Trixi Pickup',
    createdBy: 'Buckridge-Thiel',
    equipments: 'African buffalo',
    startDate: '10/09/2020',
    deadline: '17/07/2020',
    description: 'Glaucoma secondary to drugs, left eye, mild stage',
    contributor: 'MacGyver, Runolfsson and Nikolaus',
    status: true,
  },
  {
    id: 82,
    name: 'Jena Abdy',
    createdBy: 'Breitenberg, Metz and Rowe',
    equipments: 'Caracal',
    startDate: '07/02/2021',
    deadline: '14/07/2021',
    description: 'Nondisp fx of lateral condyle of unsp femr, 7thJ',
    contributor: 'Heidenreich Inc',
    status: false,
  },
  {
    id: 83,
    name: 'Ellwood Twede',
    createdBy: 'Ferry-Farrell',
    equipments: 'Asian openbill',
    startDate: '05/06/2020',
    deadline: '10/10/2020',
    description: 'Fall into natrl body of water strk bottom cause drown, subs',
    contributor: 'Gleichner, Walsh and Schmidt',
    status: false,
  },
  {
    id: 84,
    name: 'Gill Wiffield',
    createdBy: 'Murphy, Welch and Wintheiser',
    equipments: 'Nine-banded armadillo',
    startDate: '14/08/2021',
    deadline: '05/11/2021',
    description: 'Person injured in oth transport accidents involving non-mv',
    contributor: 'Lueilwitz, Streich and Dickinson',
    status: false,
  },
  {
    id: 85,
    name: 'Claudelle Stansbury',
    createdBy: 'Cruickshank LLC',
    equipments: 'Robin, white-throated',
    startDate: '10/04/2020',
    deadline: '10/10/2021',
    description: 'Puncture wound with foreign body of foot',
    contributor: 'Gerhold-Roob',
    status: false,
  },
  {
    id: 86,
    name: 'Cecilio Neve',
    createdBy: 'Hermiston, Stamm and Mayert',
    equipments: 'Baboon, yellow',
    startDate: '11/12/2020',
    deadline: '14/01/2022',
    description: 'Vitreous hemorrhage, right eye',
    contributor: 'Emard Group',
    status: false,
  },
  {
    id: 87,
    name: 'Willie Geldard',
    createdBy: 'Frami Group',
    equipments: 'Tropical buckeye butterfly',
    startDate: '05/07/2021',
    deadline: '12/10/2021',
    description: 'Traumatic compartment syndrome of upper extremity',
    contributor: 'Konopelski, Block and Dooley',
    status: false,
  },
  {
    id: 88,
    name: 'Kala Yetton',
    createdBy: 'Schneider LLC',
    equipments: "Leadbeateri's ground hornbill",
    startDate: '11/09/2020',
    deadline: '17/01/2022',
    description: 'Diffuse TBI w loss of consciousness of 1-5 hrs 59 min, subs',
    contributor: 'Yost, Terry and Farrell',
    status: false,
  },
  {
    id: 89,
    name: 'Gipsy Merveille',
    createdBy: 'Lubowitz LLC',
    equipments: 'Macaque, bonnet',
    startDate: '29/03/2021',
    deadline: '04/01/2020',
    description: 'Benign neoplasm of pituitary gland',
    contributor: 'Kozey-Stroman',
    status: true,
  },
  {
    id: 90,
    name: 'Adora Markl',
    createdBy: 'Toy, Rodriguez and Rempel',
    equipments: 'Chestnut weaver',
    startDate: '09/06/2021',
    deadline: '08/02/2021',
    description: 'Nondisp fx of nk of 5th MC bone, r hand, 7thK',
    contributor: 'Goodwin Inc',
    status: true,
  },
  {
    id: 91,
    name: 'Consuelo Vuittet',
    createdBy: 'Kuhic, Grady and Ullrich',
    equipments: 'Mudskipper (unidentified)',
    startDate: '13/07/2020',
    deadline: '11/01/2021',
    description: 'Corrosion of unspecified degree of left ankle, subs encntr',
    contributor: 'Legros-Kautzer',
    status: false,
  },
  {
    id: 92,
    name: 'Cassey Cowser',
    createdBy: 'Schumm LLC',
    equipments: 'Dolphin, common',
    startDate: '21/09/2021',
    deadline: '11/07/2021',
    description: 'Accidental malfunction of gas, air or spring-operated guns',
    contributor: 'Stoltenberg-Weber',
    status: false,
  },
  {
    id: 93,
    name: 'Layton Messent',
    createdBy: 'Gerlach, Wunsch and Stiedemann',
    equipments: 'Brocket, brown',
    startDate: '06/06/2020',
    deadline: '09/12/2019',
    description: 'Oth injuries of right wrist, hand and finger(s), sequela',
    contributor: 'Sporer-Murphy',
    status: false,
  },
  {
    id: 94,
    name: 'Enrico Baldinotti',
    createdBy: 'Treutel-Leannon',
    equipments: 'Cockatoo, long-billed',
    startDate: '25/06/2021',
    deadline: '27/02/2022',
    description: 'Takotsubo syndrome',
    contributor: 'Runte, Brakus and Renner',
    status: false,
  },
  {
    id: 95,
    name: 'Winifred Bolter',
    createdBy: 'Kirlin, Simonis and Corwin',
    equipments: 'Koala',
    startDate: '03/05/2020',
    deadline: '29/09/2020',
    description: 'Oth fracture of unsp femur, subs for clos fx w malunion',
    contributor: 'Reinger, Will and Windler',
    status: true,
  },
  {
    id: 96,
    name: 'Jessey Horwell',
    createdBy: 'Wilderman-Reinger',
    equipments: 'Toucan, white-throated',
    startDate: '01/11/2020',
    deadline: '23/04/2021',
    description: 'Disloc of unsp interphaln joint of l little finger, init',
    contributor: 'Konopelski, Dooley and Kuvalis',
    status: false,
  },
  {
    id: 97,
    name: 'Augy Ferencz',
    createdBy: 'Pollich, Pfannerstill and Effertz',
    equipments: 'Common raccoon',
    startDate: '08/04/2021',
    deadline: '01/08/2021',
    description: 'Gastroenterology and urology devices assoc w incdt',
    contributor: 'Watsica-Huels',
    status: false,
  },
  {
    id: 98,
    name: 'Katha Georgel',
    createdBy: 'Johns Group',
    equipments: 'Iguana, common green',
    startDate: '29/06/2021',
    deadline: '20/10/2020',
    description: 'Nondisp fx of medial cuneiform of left foot, init',
    contributor: 'Reichel, Ryan and Lynch',
    status: false,
  },
  {
    id: 99,
    name: 'Cornelius Kliche',
    createdBy: 'Paucek LLC',
    equipments: 'European wild cat',
    startDate: '30/12/2021',
    deadline: '10/12/2020',
    description: 'Fusion of spine, sacral and sacrococcygeal region',
    contributor: 'DuBuque-McLaughlin',
    status: true,
  },
  {
    id: 100,
    name: 'Micheline Jimenez',
    createdBy: 'Sipes, Abshire and Kiehn',
    equipments: 'Macaw, red and blue',
    startDate: '17/11/2021',
    deadline: '14/04/2021',
    description: 'Salter-Harris Type IV physeal fracture of upper end of tibia',
    contributor: 'Carter-Nicolas',
    status: true,
  },
];
